language: scala
scala:
  - 2.10.6
  - 2.11.8
matrix:
  include:
  - scala: 2.12.0-RC2
    jdk: oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
before_install:
  - export TZ=Australia/Canberra
script:
  - sbt ++$TRAVIS_SCALA_VERSION test:compile
  - echo "sbt.version=0.13.12" > project/build.properties
  - sbt ++$TRAVIS_SCALA_VERSION test:compile
  - sbt ++$TRAVIS_SCALA_VERSION clean test:compile
addons:
  apt:
    packages:
    - oracle-java8-installer
